### ISSUE TITLE
Hall of mirrors effect in q3dm8 with OpenGL 2

### ISSUE THREAD

**Issue by rohit-n** [ioquake/ioq3#115]
Using an Nvidia GTX 670. This issue only occurs in and near this room, and not with OpenGL1.

http://i.imgur.com/cGmZREM.jpg

**Comment by SmileTheory** [comment]
Does https://github.com/ioquake/ioq3/commit/40cfbc9a8246ab2ea6b2f05f5043de70eb5ad980 fix it for you?

**Comment by KuehnhammerTobias** [comment]
40cfbc9 does fix this issue (at least for me).
I reported this issue already here: https://bugzilla.icculus.org/show_bug.cgi?id=6350
Question: should OpenGL2 issues reported here or at icculus bugzilla?
Since 40cfbc9 doesn't fix issue https://bugzilla.icculus.org/show_bug.cgi?id=6363 I have to modify the issue report. Better close the issue and move it to here or modify?

**Comment by rohit-n** [comment]
Yes, the issue looks fixed. I'll close this.

**Comment by TimeDoctor** [comment]
*Better close the issue and move it to here or modify?*

Please do not move bugs between the systems. Bugzilla on icculus.org is not going away.
