### ISSUE TITLE
Dynamic lighting is broken

### ISSUE THREAD

**Issue by coltongit** [ioquake/ioq3#179]
I noticed in ioquake3 (the latest git) that the dynamic lighting is broken. Can someone please figure out where the bug is in the renderer dlls (if there is any making this bug happen) & fix it?

**Comment by timangus** [comment]
Worst. Bug report. Ever.

**Comment by TimeDoctor** [comment]
Please give us a screenshot of the bug so that we can reproduce it and repair it.

**Comment by coltongit** [comment]
I'll tell you how to reproduce it. Step 1: Grab sst13's d-light map. Step
2: Load the map. Step 3: Witness the broken dynamic lighting. Easy as 1, 2,
3, isn't it?

**Comment by TimeDoctor** [comment]
Without a screenshot of exactly what you see so that we know we're seeing the right bug and can verify it is fixed, the steps to reproduce (which you've given us now), and a link to whatever files are required ( now that we now we need some extra map pk3) it is not going to be fixable.

**Comment by coltongit** [comment]
Here's the link to the map: http://sst13.de/map-d-light.pk3

**Comment by jpcy** [comment]
This is fixed in ioquake3, but you need to use the ioquake3 cgame vm.

Vanilla quake 3 incorrectly keeps mover light color in the 0-255 range instead of 0-1 which all other dlights use. See [here](https://github.com/id-Software/Quake-III-Arena/blob/master/code/cgame/cg_ents.c#L142) and [here](https://github.com/ioquake/ioq3/blob/master/code/cgame/cg_ents.c#L142).

**Comment by TimeDoctor** [comment]
Thanks jpcy.

**Comment by coltongit** [comment]
Thanks for letting me know about this... I will use a fresh compile of the q3 vm's from here on in...

**Comment by ensiform** [comment]
Mind you, the VMs only work locally or on servers running those VMs with pure server enabled.
