### ISSUE TITLE
build exit with error because  cant be negative define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1

### ISSUE THREAD

**Issue by tlosm** [ioquake/ioq3#184]
i face it on Quad G5 and On X5000 too ..
this is in /libcurl-7.35.0/curlrules.h

dont build exit with error because this cant be negative
# define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
# define CurlchkszGE(t1, t2) sizeof(t1) >= sizeof(t2) ? 1 : -1

i switched in:
# define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : 1
# define CurlchkszGE(t1, t2) sizeof(t1) >= sizeof(t2) ? 1 : 1

and build was continue

**Comment by smcv** [comment]
> dont build exit with error because this cant be negative

**What** can't be negative? Please quote the exact error. The specifics matter.

```
#define CurlchkszGE(t1, t2) sizeof(t1) >= sizeof(t2) ? 1 : 1
```

This is almost certainly not correct. You're working around a symptom without fixing the underlying issue; the code in question compiles but is probably wrong, and is likely to crash or behave incorrectly. It might even be an exploitable security flaw.

**Comment by tlosm** [comment]
yes im sure about ... but was the only way for made the build continue ... was just a fast experiment ;-)

**Comment by smcv** [comment]
@tlosm: you have not provided enough information for someone not using PowerPC (which I'm guessing no regular ioquake3 contributors do) to fix this bug. I don't know what you expect the ioquake3 maintainers to do about it, but at the moment there's no way it's going to get fixed.

If you want this to be fixed, please provide more information, including the complete error messages seen. The details are important, and the information you have given so far is not enough to be useful.

Or, if you don't care about this being fixed, why did you report it at all?

**Comment by tlosm** [comment]
[curlrules.h.zip](https://github.com/ioquake/ioq3/files/257645/curlrules.h.zip)
Fixed and buld on PPC64 no Altivec machine

**Comment by smcv** [comment]
The change in `curlrules.h.zip`, in a more useful format, is:

```diff
diff --git a/code/libcurl-7.35.0/curl/curlrules.h b/code/libcurl-7.35.0/curl/curlrules.h
index 7c2ede3..8f8521c 100644
--- a/code/libcurl-7.35.0/curl/curlrules.h
+++ b/code/libcurl-7.35.0/curl/curlrules.h
@@ -129,7 +129,7 @@
  * Macros private to this header file.
  */
 
-#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : -1
+#define CurlchkszEQ(t, s) sizeof(t) == s ? 1 : 1
 
 #define CurlchkszGE(t1, t2) sizeof(t1) >= sizeof(t2) ? 1 : -1
 
```

This is the same change that you described in the initial bug report, and I already explained why this is wrong. To be absolutely clear in case you missed it the first time:

* This is the wrong change.
* This change is not suitable for merging.
* This change is a workaround, not a solution. libcurl is reporting that an assumption made by some header is not true, and instead of giving us enough information to locate and fix that wrong assumption, you have made libcurl stop checking whether several of its assumptions are true.
* Showing us this change does not give us enough information to know what the right change is.

It'll be one of these: either the `long` type is smaller than `CURL_SIZEOF_LONG`, or the `curl_off_t` type is smaller than `CURL_SIZEOF_CURL_OFF_T`, or the `curl_socklen_t` type is smaller than `CURL_SIZEOF_CURL_SOCKLEN_T`.

Please **show us the actual, specific, error message that you see when you compile without this change**. For this to be fixed correctly, we need to see the line numbers; we need to see the small details; we need to see the whole message. Telling us your interpretation of one part of it is **not enough to be useful**.

The classic essay on this topic is [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by zturtleman** [comment]
Duplicate of #298 which has compile log.
