### ISSUE TITLE
Override default master for the in-game GUI and fix server DNS caching issue

### ISSUE THREAD

**Issue by TimeDoctor** [ioquake/ioq3#188]
![master server](https://cloud.githubusercontent.com/assets/903791/15417641/f19ece52-1df3-11e6-9c58-d1fe35f2d09f.png)
The default master server of master.quake3arena.com appears to be down permanently. Players/clients are not able to use the default in-game server browser. We need to override this configuration in all cases  to point to master.ioquake3.org as well as solving the caching issue in #161 

Servers should still report to master.quake3arena.com in case it comes back online.

**Comment by ensiform** [comment]
You could swap the defaults.  Master 1 being our master and 2 being the id master.

**Comment by TimeDoctor** [comment]
I believe that our game code already does this, but it might need to be implemented at another level to override the in-game browser when we aren't shipping a new pk3/after you connect to a pure server and exit back to the menu.

**Comment by zturtleman** [comment]
`Servers: Internet` in vanilla UI and ioq3 UI is sv_master1 (id Software). Internet2 in ioq3 UI is ioquake3 master. See cvar init in [sv_init.c](https://github.com/ioquake/ioq3/blob/615b732/code/server/sv_init.c#L679).

I think the best option is switching them which solves the issue, as suggested by Ensiform.

As a side note, it also swaps masters used by Internet 1 and 2 in ioq3 UI. As it stands, even if using ioq3 UI some people may not be able to access ioq3 master because historically sv_master2 was archived as "" (blank). After swapping sv_master1 and 2, people with blank sv_master2 will have ioq3 master instead of id master available to use in ioq3 UI.

**Comment by ensiform** [comment]
Force a reset?  If blank?

**Comment by coltongit** [comment]
Guys, it went back up so we're good for the meantime on this issue. Keep it open however if it shuts down again.

**Comment by TimeDoctor** [comment]
the default master still needs to change to ours since we can be more responsive to downtime, and we still need to stop caching the DNS result forever.

**Comment by ensiform** [comment]
Sponge would be the person to talk to if it goes down again.

**Comment by wtfbbqhax** [comment]
Why not have servers report strictly to ioq3 master, and then have client query from both? 

With consideration to servers broadcasting to both masters; merging them etc.. (now curious if servers are reporting both ip4/ip6 and whether this shows dup servers in list).

**Comment by ensiform** [comment]
The list skips duplicates in ioq3 client.

**Comment by TimeDoctor** [comment]
The id master is down again, although #161 is solved we still need to resolve the issue for the in-game GUI.

**Comment by zturtleman** [comment]
In-game GUI server browser fixed in https://github.com/ioquake/ioq3/commit/9f239d647b5e7d21e437ad6f012af436b30bb456.
