### ISSUE TITLE
Com_QueueEvent: overflow when moving high poll frequency mice during loading

### ISSUE THREAD

**Issue by llbraughler** [ioquake/ioq3#191]
This occurs when moving the mouse during loading with a high frequency mouse (for example, a Razer Deathadder running at 1000 Hz). The console is spammed with `Com_QueueEvent: overflow`.

**Comment by ec-** [comment]
Modern mice have hi-frequency polling that feeds game engine with a lot of data during movements. So if you have 1000Hz mouse - even 250ms frame delay may cause such overflow. 
Solution is simple: you should combine all sequential mouse moves (but not key events!) in one event - it is safe because engine uses accumulated delta anyway. With such approach it is almost impossible to cause such overflow except that you can click 100 times per second or so
[fix.txt](https://github.com/ioquake/ioq3/files/378067/fix.txt)

**Comment by ensiform** [comment]
I just have it print once instead of spamming in OpenJK.

**Comment by ensiform** [comment]
@ec- I just tested your patch in OpenJK and it causes the mouse to not function very well if at all.  The mouse just moves a couple of pixels when moving my mouse around.  Sounds like the code isn't actually set up to handle delta very well?

**Comment by ensiform** [comment]
Its the same code.

**Comment by zturtleman** [comment]
Fixed in https://github.com/ioquake/ioq3/commit/be1c71d36306637490348a128ecc2245b909c5da.
