### ISSUE TITLE
Issue building on Win10/mingw

### ISSUE THREAD

**Issue by budleigh** [ioquake/ioq3#248]
I'm seeing the following building on Win10 with mingw/msys:

DED_CC code/sys/sys_win32.c
code/sys/sys_win32.c: In function 'Sys_SteamPath':
code/sys/sys_win32.c:146:165: error: 'KEY_WOW64_64KEY' undeclared (first use in this function)
  if (!steamPath[0] && !RegOpenKeyEx(HKEY_LOCAL_MACHINE, "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Steam App " STEAMPATH_APPID, 0, KEY_QUERY_VALUE | KEY_WOW64_64KEY, &steamRegKey))
                                                                                                                                                                     ^
code/sys/sys_win32.c:146:165: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [build/release-mingw32-x86/ded/sys_win32.o] Error 1
make[2]: Leaving directory `/c/Users/argue/OneDrive/Documents/GitHub/ioq3'
make[1]: *** [targets] Error 2
make[1]: Leaving directory `/c/Users/argue/OneDrive/Documents/GitHub/ioq3'
make: *** [release] Error 2

Googling around hasn't yielded much.

**Comment by SmileTheory** [comment]
Have you applied some sort of patch to your code?  Because looking at https://github.com/ioquake/ioq3/blob/master/code/sys/sys_win32.c#L146 and its history, that value has always been KEY_WOW64_32KEY, not KEY_WOW64_64KEY.

Anyway, according to the headers I have, both of those values are #define'd in winnt.h, which is #include'd in windef.h as long as NT_INCLUDED isn't #define'd, which is #include'd in windows.h, and looking at https://github.com/ioquake/ioq3/blob/master/code/sys/sys_win32.c#L27 , windows.h is #include'd, so unless something else is #define'ing NT_INCLUDED I don't see what could be going wrong.

Are you using the latest msys2?

**Comment by budleigh** [comment]
Sorry, the 64_64 was something I'd tried, it is supposed to be 64_32. I used the msys linked in the mingw build docs, is that the wrong one now?

**Comment by SmileTheory** [comment]
if you mean http://wiki.ioquake3.org/Building_ioquake3_on_Windows_-_mingw_and_msys , that's fairly outdated.  I personally use https://msys2.github.io/ , but I don't have a handy tutorial for it on hand.  Alternately you could use Cygwin, for which MANATARMS made a tutorial at http://discourse.ioquake.org/t/how-to-build-ioquake3-using-cygwin/223 which should still work.

**Comment by SmileTheory** [comment]
So since there wasn't a tutorial, I wrote up how I make binaries on windows with msys2:

http://wiki.ioquake3.org/Building_ioquake3_on_Windows_-_msys2

Are there any other issues?

**Comment by budleigh** [comment]
Awesome. I ended up getting it to work with cygwin based on the previous documentation, but having the MSYS2 docs is going to be really helpful going forward. Thanks so much for your help!
