### ISSUE TITLE
"pak0.pk3" is missing

### ISSUE THREAD

**Issue by CitoplasmaX** [ioquake/ioq3#292]
echedey@echedey-500-500ns:~/Documentos/Proyectos/MELA The Game/Engine/ioq3/build/release-linux-x86_64$ ./ioquake3.x86_64
ioq3 1.36 linux-x86_64 Jun  3 2017
SSE instruction set enabled
----- FS_Startup -----
We are looking in the current search path:
/home/echedey/.q3a/baseq3
./baseq3

----------------------
0 files in pk3 files
"pak0.pk3" is missing. Please copy it from your legitimate Q3 CDROM. Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable

**Comment by TimeDoctor** [comment]
You need to own Quake 3 to play it. Please direct support questions to our forum http://discourse.ioquake.org/
And check out our players guide
http://wiki.ioquake3.org/Players_Guide

**Comment by CitoplasmaX** [comment]
...but ioquake3 was a game engine based on quake3...

**Comment by ensiform** [comment]
It's only the source code, you must have a legitimate copy of Quake3 or a subsequent standalone game.

**Comment by TimeDoctor** [comment]
Yes, the quake 3 source code is free but the game is not. In order to play quake 3 using the ioquake3 engine you need to own a copy of the game or you can play other free games based on this engine. This is not a support forum, please request any further assistance on our forums at http://discourse.ioquake.org/
