### ISSUE TITLE
Team Arena CD key field starts filled with spaces

### ISSUE THREAD

**Issue by zturtleman** [ioquake/ioq3#392]
Entering Team Arena CD key requires deleting space characters first. This is not obvious since the text cursor is always placed at the beginning of the edit field when it's selected.

Inability to enter Team Arena CD key was reported on the forum at https://discourse.ioquake.org/t/cant-enter-team-arena-cd-key/1204.

**Comment by AaronRobson** [comment]
I'm no expert at the C language, but I suspect the issue is down to the value that `CL_CDKeyValidate` places in `cl_cdkey` here: https://github.com/ioquake/ioq3/blob/master/code/qcommon/common.c#L2463-L2487 and the initialisation here https://github.com/ioquake/ioq3/blob/master/code/qcommon/common.c#L2449-L2456 it isn't clear to me that it should be filled with spaces. Also the amount of spaces seems to differ from 16 to 33.
