### ISSUE TITLE
Help with JS build mode, CDN support?

### ISSUE THREAD

**Issue by megamindbrian** [ioquake/ioq3#419]
I have been mulling over this for a bit and gotten nowhere. QuakeJS needs to add CDN support. I love the idea of improving the pipeline but I have no idea how this engine is used or anything about the current community.

These features make sense to me:
1) manifest file for splitting individual maps into separate PK3s (works in a Google bucket)
2) transcoding to ogg and injecting into new PK3s
3) adding an HTTP redirect to server downloads (not implemented by QuakeJS now, I thought this would make more sense to do in C, rather than JS).

The branch I am hoping to PR is here:
https://github.com/megamindbrian/ioq3/commits/ioq3-quakejs

**Comment by TimeDoctor** [comment]
I'm not sure you opened this on the right fork, this is the ioquake3 project fork that you've opened this issue on. We have number 3, http redirects, we have opus support ni number 2 to some extent (mainly for voip), I have no idea what a manifest file for google bucket is or why we would want it.

**Comment by TimeDoctor** [comment]
I will say that I want to get ioquake3 web embedded and it's sad that all of the fun is only on other forks,

**Comment by megamindbrian** [comment]
OpenArena might want to rebase after this to get the JS build, I think it's awesome.

https://quake.games/?set%20name%20Name

**Comment by TimeDoctor** [comment]
I guess this isn't an issue for ioquake3, let me know if I'm mistaken, I would welcome work to use SDL 2 and web standards.

**Comment by briancullinan** [comment]
@TimeDoctor More than a few people have reached out to me for supporting this build mode. This feature would be similar to Unreal's emscripten build which has actually been put on the back-burner as well. I think there is definitely a demand for a stable JS build mode to coincide with the WIN/*NIX/MAC builds. I would be overjoyed if you reopened this as "In Progress", it has already brought some prestige.

I am working on 2 tasks, removing the manifest functionality AND rewriting the repack.js tool to use the dedicated build as a tool for graphing the assets maps (e.g. which textures/sounds). This tool would help mod creators convert and split out assets in to the correct PK3 files. This is necessary in order to get the game up and running as quickly as possible in the browser. Currently, Quake 3 bundles maps into pak0.pk3 along with all the other materials such as QVMs, UI menus, file-system layering, etc.

The reason the manifest is necessary in the QuakeJS build is because the client web-browser does not know what files it needs when it first starts (it assumes pak0-pak8 I think), there is a virtual filesystem that is empty. I am thinking `COM_HintFilesystem` which lists out which PK3 files are currently loaded and sends the CVar to the client. Please, if you could explain any further, if this is already being done in the code, or how a CDN type redirect is sent to the cUrl module, I would really appreciate it. My understanding is server administrators have to run some sort of proxy in order to get clients to download from somewhere else. Any advice? I would be really grateful.

**Comment by briancullinan** [comment]
Progress! I've got the build modes isolate so I can build for Native Win/Nix/OSX or build for JS without having to switch branches. I might be missing a few changes but all EMSCRIPTEN changes are isolated with `#ifdef EMSCRIPTEN`
