### ISSUE TITLE
Inconsistent Low Ammo Warning

### ISSUE THREAD

**Issue by Joz3d** [ioquake/ioq3#454]
Low Ammo Warning/Out of Ammo only shows maybe ~20% of the time.

FFA DM
Linux

**Comment by TimeDoctor** [comment]
are you using a build provided by your distribution, one you've compiled yourself, or one from ioquake3.org?

**Comment by Joz3d** [comment]
Both, actually.  Have a build from Ubuntu 19.10 repo, but my buddy also forked this repo (for some modifications with VOIP) so am also running that modified build.  I checked and both versions have the issue.

**Comment by Calinou** [comment]
As in the vanilla game, the "low ammo warning" dialog uses some kind of smart logic that makes it only display if the sum of all ammo in *all* owned weapons is below a certain threshold. If you have 100 bullets but only 1 rocket while using the rocket launcher, you won't see a low ammo warning.

This is different from Quake Live where the low ammo warning works on a purely per-weapon basis. (Which turned out to be a much better idea in hindsight.)

**Comment by Joz3d** [comment]
What!?  Ok that's... lame.  Thanks @Calinou I verified the functionality in the manner you described.
