### ISSUE TITLE
`#if defined (__i386__) || defined(__x86_64__)` fails in Visual Studio (misc/msvc142)

### ISSUE THREAD

**Issue by kungfooman** [ioquake/ioq3#538]
As far as I can see, this VS solution was introduced here: https://github.com/ioquake/ioq3/commit/de055995d0bba9d0f8e6bbd910618bee57344b6d

It creates a linker error, because both ifdefs are always false:

![image](https://user-images.githubusercontent.com/5236548/147952987-bbab464b-ca07-4658-bb37-7a2c8aca229b.png)

Based on https://sourceforge.net/p/predef/wiki/Architectures/ the latter predefinition is only available on GNU C / Sun Studio. But then how did it even work for @tomkidd?

**Comment by tomkidd** [comment]
As both the new VS2019 project and the updates for Apple Silicon support contained an SDL upgrade, they went in at roughly the same time. Although I tried to make sure they didn't collide on anything, I guess that was unsuccessful. 

This code causing the linker error is designed to make sure this code only works on Intel devices, introduced so that Mac builds for Apple Silicon skip it. These macros exist on macOS and/or are set by the Makefile which is how ioq3 is built most often. 

If you set `__i386__` as a preprocessor directive in Visual Studio's settings for the quake3 project the build should continue. I'll confer with folks as to whether or not this is the best long term solution.

**Comment by zturtleman** [comment]
`__i386__` is defined by GCC and Clang. MSVC uses a different define. It's probably just well to check `#ifndef __arm__` here (assuming it works on Apple Silicon, untested) and add a comment about Xcode project needing to disable the file on Apple Silicon instead of playing wack-a-mole with x86 defines to workaround Xcode compiling it for the wrong architecture.

**Comment by DanielGibson** [comment]
What exactly is going wrong here anyway?

Is this `#if defined (__i386__) || defined(__x86_64__)` really only needed for "AppleSilicon"?
If so - why? Why not for Linux ARM, Linux PPC, etc? Doesn't this mean there's a "proper" solution like only using that file (I assume this is about code/qcommon/vm_x86.c) for x86(_64) builds?

If a "proper" solution isn't possible for some reason, could the platform-#defines from code/qcommojn/q_platform.h (`id386`, `idx64`) be used?

**Comment by zturtleman** [comment]
Based on https://github.com/ioquake/ioq3/pull/481, the Xcode project includes vm_x86.c and targets x86_64 and Apple Silicon. Tom Kidd didn't find a way to only compile files for one architecture in the Xcode project.

Checking architecture in vm_x86.c is a hack for Xcode Apple Silicon support and no other build system should depend on it. It only needs to disable the file for Xcode Apple Silicon so it's dealing with a known compiler/arch to disable opposed to how to allow all x86/x86_64 compilers which are all that _should be_ compiling this file. My thought was that disabling it for Apple Silicon would not risk breaking other compilers due to Xcode project shenanigans.

id386 seems to be for enabling assembly routines. Defining C_ONLY disables it.

https://sourceforge.net/p/predef/wiki/Architectures/ lists a lot of defines for checking for x86 but in reality checking GNU C and MSVC x86 and x86_64 defines as kungfooman indirectly indicated is probably fine. Try adding `|| defined(_M_IX86) || defined(_M_X64)` (untested). After all, more x86[_64] compiler defines can always be added if they turn up. (It doesn't matter to me either way.)

**Comment by DanielGibson** [comment]
> Tom Kidd didn't find a way to only compile files for one architecture in the Xcode project.

Ah, makes sense!

> id386 seems to be for enabling assembly routines. Defining C_ONLY disables it.

Ok, I missed that, that's a pity

> Try adding || defined(_M_IX86) || defined(_M_X64) (untested). After all, more x86[_64] compiler defines can always be added if they turn up.

Sounds good to me!
