### ISSUE TITLE
Why issue #551 was closed?

### ISSUE THREAD

**Issue by Ilyaololo** [ioquake/ioq3#560]
Why PR #551 was be closed without comment?

**Comment by oitzujoey** [comment]
There are some questions you just don't ask…

It's because it allows the code to be compiled for a Russian CPU.

I will periodically archive this discussion for future reference.
[http://web.archive.org/web/https://github.com/ioquake/ioq3/issues/560](http://web.archive.org/web/https://github.com/ioquake/ioq3/issues/560)
