### ISSUE TITLE
CPU usage benchmark

### ISSUE THREAD

**Issue by zamazan4ik** [ioquake/ioq3#609]
Hi!

I am trying to evaluate Profile-Guided Optimization (PGO) benefits for the game domain, so I built ioq3 with Clang's PGO. But the main question - is there a way to somehow bench the game? Especially, I am interested in benchmarking CPU usage.

If you have ideas, on how it's possible to do this - please let me know. Maybe some ready-to-use bench suites/scenarios/tools/a piece of advice - anything would be helpful.

Thanks in advance.

**Comment by NuclearMonster** [comment]
If you have a copy of quake 3 arena you can run the game and there is a default demo included with it that can function as a benchmark or you can record your own. It is easily repeatable and you can even launch it from the command line. With something like `+demo demofile`

You can also issue those commands using the console in game (bring it down with the key to the left of the 1 key or shift+escape) like:
`/demo` play a demo
`/record` record a demo
`/stopdemo` stop recording the demo

All of these can also be bound to in-game keys. 

Two things of note:
1) A demo is the term from the time this game was made for recording gameplay in a replayable format. Before there was YouTube and other video hosting services, you could record a demo and others could play it back and see what happened in a match of quake 3.

2) The CPU usage of ioquake3 is largely trivial at this point. While I'm sure someone could optimize more for today's processors and attempt to split the load from the single threaded era, it's _almost_ pointless to work on. Not that someone shouldn't, because you can always have fun working on quake 3 and add more to fill or raise up that performance and match modern processors, but that from a performance perspective is just how it is at present.

Good luck and let us know on our forums if you run into any trouble or just want to discuss it further: https://discourse.ioquake.org/

**Comment by zamazan4ik** [comment]
Yeah - seems like exactly what I need! Definitely will try Minetest as well. Thanks a lot for the idea!

But I will try it only after playing with Quake3d - it's quite funny to compile and play with a game from my childhood ;)
